# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  coresb:
    image: coresb
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5002:5002
