# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  coresb:
    image: coresb
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5002:5002
  sqldb:
    container_name: MSSQLCoreSB
    image: mcr.microsoft.com/mssql/server
    ports: 
        - 1433:1433
    environment: 
        SA_PASSWORD: "coresbQ1"
        ACCEPT_EULA: "Y"