FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /CoreSB
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["CoreSB.csproj", "."]
RUN dotnet restore "./CoreSB.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "CoreSB.csproj" -c Release -o /CoreSB/build

FROM build AS publish
RUN dotnet publish "CoreSB.csproj" -c Release -o /CoreSB/publish

FROM base AS final
WORKDIR /CoreSB
COPY --from=publish /CoreSB/publish .
ENTRYPOINT ["dotnet", "CoreSB.dll"]
